name: Build

on: [ push, pull_request, workflow_dispatch ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Generate resourcepacks
        run: $GITHUB_WORKSPACE/scripts/generate_resourcepacks.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Resourcepacks
          path: target/resourcepack_v*.zip
