name: Deploy

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate resourcepacks
        run: $GITHUB_WORKSPACE/scripts/generate_resourcepacks.sh

      - name: Setup Release assets directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/.github/release_assets
          mv $GITHUB_WORKSPACE/target/resourcepack_v3.zip $GITHUB_WORKSPACE/.github/release_assets/
          mv $GITHUB_WORKSPACE/target/resourcepack_v4.zip $GITHUB_WORKSPACE/.github/release_assets/

      - name: Generate signatures
        run: |
          sha1sum $GITHUB_WORKSPACE/.github/release_assets/resourcepack_v3.zip | cut -b -32 \
          > $GITHUB_WORKSPACE/.github/release_assets/resourcepack_v3.zip.sha1
          sha1sum $GITHUB_WORKSPACE/.github/release_assets/resourcepack_v4.zip | cut -b -32 \
          > $GITHUB_WORKSPACE/.github/release_assets/resourcepack_v4.zip.sha1

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Upload Release assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: $GITHUB_WORKSPACE/.github/release_assets
