name: Test

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate resourcepacks
        run: $GITHUB_WORKSPACE/scripts/generate_resourcepacks.sh
